// Re-export de todos los tipos inferidos del schema Zod
export type {
  MaterialId,
  MaterialSpec,
  BackPanelSpec,
  DoorType,
  DoorSystem,
  Zocalo,
  Maletero,
  Structure,
  HangingVariant,
  HangingModule,
  DrawerVariant,
  DrawerModule,
  ShelvingModule,
  Module,
  Section,
  Dimensions,
  PlacardMetadata,
  PlacardConfig,
  AISuggestion,
} from "@/schemas/wardrobe-schema";
